; ROM offsets
FM_INSTRUMENTS_ROM_OFFSET              equ 01EB000h
PCM_BANK_0_ROM_OFFSET                  equ 01E0000h
PCM_BANK_1_ROM_OFFSET                  equ 01E8000h
MUSIC_BANK_0_POINTER_TABLE_ROM_OFFSET  equ 01F8000h
MUSIC_BANK_1_POINTER_TABLE_ROM_OFFSET  equ 01F0000h
SFX_POINTER_TABLE_ROM_OFFSET           equ 01EE000h
; Additional ROM Offsets can be added for new assets
PCM_BANK_2_ROM_OFFSET                  equ 0200000h
MUSIC_BANK_2_POINTER_TABLE_ROM_OFFSET  equ 0208000h
MUSIC_BANK_3_POINTER_TABLE_ROM_OFFSET  equ 0210000h

; Computed constants
FM_INSTRUMENTS_BANK_INDEX      equ FM_INSTRUMENTS_ROM_OFFSET/08000h
FM_INSTRUMENTS_BANK_OFFSET     equ FM_INSTRUMENTS_ROM_OFFSET#08000h+08000h
PCM_BANK_0_INDEX               equ PCM_BANK_0_ROM_OFFSET/08000h
PCM_BANK_1_INDEX               equ PCM_BANK_1_ROM_OFFSET/08000h
MUSIC_BANK_0_INDEX             equ MUSIC_BANK_0_POINTER_TABLE_ROM_OFFSET/08000h
MUSIC_BANK_0_OFFSET            equ MUSIC_BANK_0_POINTER_TABLE_ROM_OFFSET#08000h+08000h
MUSIC_BANK_1_INDEX             equ MUSIC_BANK_1_POINTER_TABLE_ROM_OFFSET/08000h
MUSIC_BANK_1_OFFSET            equ MUSIC_BANK_1_POINTER_TABLE_ROM_OFFSET#08000h+08000h
SFX_BANK_INDEX                 equ SFX_POINTER_TABLE_ROM_OFFSET/08000h
SFX_BANK_OFFSET                equ SFX_POINTER_TABLE_ROM_OFFSET#08000h+08000h
; Additional computed constants
PCM_BANK_2_INDEX               equ PCM_BANK_2_ROM_OFFSET/08000h
MUSIC_BANK_2_INDEX             equ MUSIC_BANK_2_POINTER_TABLE_ROM_OFFSET/08000h
MUSIC_BANK_2_OFFSET            equ MUSIC_BANK_2_POINTER_TABLE_ROM_OFFSET#08000h+08000h
MUSIC_BANK_3_INDEX             equ MUSIC_BANK_3_POINTER_TABLE_ROM_OFFSET/08000h
MUSIC_BANK_3_OFFSET            equ MUSIC_BANK_3_POINTER_TABLE_ROM_OFFSET#08000h+08000h

; entries ordered by starting index
BANK_TABLE:
    dw  001h, MUSIC_BANK_0_INDEX, MUSIC_BANK_0_OFFSET, BANK_TYPE_MUSIC
    dw  021h, MUSIC_BANK_1_INDEX, MUSIC_BANK_1_OFFSET, BANK_TYPE_MUSIC
    dw  02Ah, MUSIC_BANK_2_INDEX, MUSIC_BANK_2_OFFSET, BANK_TYPE_MUSIC
    dw  041h, SFX_BANK_INDEX,     SFX_BANK_OFFSET,     BANK_TYPE_SFX
    dw  081h, MUSIC_BANK_3_INDEX, MUSIC_BANK_3_OFFSET, BANK_TYPE_MUSIC
    dw  0FFh